name: PR
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Build
        run: go build

      - name: Setup Lint
        run: curl -LO https://github.com/golangci/golangci-lint/releases/download/v1.30.0/golangci-lint-1.30.0-linux-amd64.tar.gz && tar -xf golangci-lint-1.30.0-linux-amd64.tar.gz

      - name: Lint
        run: golangci-lint-1.30.0-linux-amd64/golangci-lint run
